/* Generated by Together */

/**
 * For a description of University member permits, follow hyperlink to the Administration
 * use case for issuing a new University member permit.
 */
public class University_member_permit extends Permit {
   private String visitday;
    private String permitType;
   
    //Constructor

    public University_member_permit(String a, String a1) {
        super(a);
        visitday = a1;
        permitType = "University member visitor";
        setPermitType(permitType);
        setVisitday(a1);
    }

    @Override
    public String toString() {
        return "University_member_permit{" + "visitday=" + visitday + ", permitType=" + permitType + '}';
    }

   

    

    
}
