/* Generated by Together */


public class Vehicle_info {
    /**
     * The vehicle's registration number.
     */
    private String regNo;
    private String carName;
    private String carColor;
    private String cartype;
    private String carModel;
    private Permit lnkPermit;
    private String noentries;
    private String noWarning;
    
   //Constructor

    public Vehicle_info(Permit paramPermit,String ss,String ss1,String ss2,String ss3,String ss4,String ss5,String ss6) {
         
      regNo =ss;
      carName = ss1; 
      carColor= ss2;
      cartype = ss3;
      carModel= ss4;
      noentries= ss5;
      noWarning= ss6;
      lnkPermit = paramPermit;
    }
    //Get Methods

  public String getPermitType()
  {
    return lnkPermit.getPermitType();
  }
  public Permit getPermit()
  {
    return lnkPermit;
  }  
  public String getVisitday() 
  {
    return lnkPermit.getVisitday();
  }
  public String getEndday() 
  {
    return lnkPermit.getEndday();
  }


    @Override
    public String toString() {
        return "Vehicle_info{" + "regNo=" + regNo + ", carName=" + carName + ", carColor=" + carColor + ", cartype=" + cartype + ", carModel=" + carModel + ", lnkPermit=" + lnkPermit + ", noentries=" + noentries + ", noWarning=" + noWarning + '}';
    }
 
   

   

    
   
}
